name: Build and Push Mock API

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-scan-push:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_TAG: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set lowercase repository name
        run: |
          echo "REPO_NAME=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.REPO_NAME }}:${{ env.IMAGE_TAG }} .

#      - name: Run Trivy vulnerability scanner
#        uses: aquasecurity/trivy-action@master
#        with:
#          scan-type: 'image'
#          image-ref: '${{ env.REGISTRY }}/${{ env.REPO_NAME }}:${{ env.IMAGE_TAG }}'
#          format: 'table'
#          exit-code: '1'
#          ignore-unfixed: true
#          severity: 'CRITICAL,HIGH'
#          scanners: 'vuln'

      - name: Push Docker image
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.REPO_NAME }}:${{ env.IMAGE_TAG }}
          docker tag ${{ env.REGISTRY }}/${{ env.REPO_NAME }}:${{ env.IMAGE_TAG }} ${{ env.REGISTRY }}/${{ env.REPO_NAME }}:latest
          docker push ${{ env.REGISTRY }}/${{ env.REPO_NAME }}:latest