name: Build and Push Mock API

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  # Convert repository name to lowercase
  IMAGE_NAME: ${{ lower(github.repository) }}
  IMAGE_TAG: test

jobs:
  build-scan-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

#      - name: Run Trivy vulnerability scanner
#        uses: aquasecurity/trivy-action@master
#        with:
#          scan-type: 'image'
#          image-ref: '${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}'
#          format: 'table'
#          exit-code: '1'
#          ignore-unfixed: true
#          severity: 'CRITICAL,HIGH'
#          scanners: 'vuln'

      - name: Push to GHCR
        run: |
          IMAGE_PATH=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker tag ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} ${{ env.REGISTRY }}/$IMAGE_PATH:latest
          docker push ${{ env.REGISTRY }}/$IMAGE_PATH:latest